### PR TITLE
Adds cropping

### LINKED ISSUE #4: Crop Image
Great Lib :)

Any plans to add the possibility to crop the Image?

### PR DESCRIPTION
**Pull request by sammy-SC**
resolves https://github.com/makomori/Sharaku/issues/4

I add cropping, i copied code for cropping from https://github.com/sprint84/PhotoCropEditor?ref=ioscookies.com

This is work in progress, any suggestions are welcome.

### CODE REVIEW

**Comment by sammy-SC** [comment]
@makomori i was thinking about adding few more options for image editing, just like Instagram does it.
Maybe brightness and contract to start with.

img_1198

Would you be open to that?

**Comment by makomori** [comment]
@sammy-SC Thank you for the proposal! But I'm not thinking about adding features like that, at least at this time.

**Comment by BhavinBhadani** [comment]
@sammy-SC  nice . do u have or make that type of library or can u help me on it?

**Comment by sammy-SC** [comment]
@BhavinBhadani I think there is already such a library -> https://github.com/Yummypets/YPImagePicker

**Pull request closed without merging**
